```{r}
library(dplyr)
library(ggplot2)
```

```{r}
# 设置文件路径
file1 <- "data/Data_SubmitRecord/SubmitRecord-Class1.csv"
file2 <- "data/Data_SubmitRecord/SubmitRecord-Class2.csv"
file3 <- "data/Data_SubmitRecord/SubmitRecord-Class3.csv"
file4 <- "data/Data_SubmitRecord/SubmitRecord-Class4.csv"
file5 <- "data/Data_SubmitRecord/SubmitRecord-Class5.csv"
file6 <- "data/Data_SubmitRecord/SubmitRecord-Class6.csv"
file7 <- "data/Data_SubmitRecord/SubmitRecord-Class7.csv"
file8 <- "data/Data_SubmitRecord/SubmitRecord-Class8.csv"
file9 <- "data/Data_SubmitRecord/SubmitRecord-Class9.csv"
file10 <- "data/Data_SubmitRecord/SubmitRecord-Class10.csv"
file11 <- "data/Data_SubmitRecord/SubmitRecord-Class11.csv"
file12 <- "data/Data_SubmitRecord/SubmitRecord-Class12.csv"
file13 <- "data/Data_SubmitRecord/SubmitRecord-Class13.csv"
file14 <- "data/Data_SubmitRecord/SubmitRecord-Class14.csv"
file15 <- "data/Data_SubmitRecord/SubmitRecord-Class15.csv"

# 读取 CSV 文件
data1 <- read.csv(file1)
data2 <- read.csv(file2)
data3 <- read.csv(file3)
data4 <- read.csv(file4)
data5 <- read.csv(file5)
data6 <- read.csv(file6)
data7 <- read.csv(file7)
data8 <- read.csv(file8)
data9 <- read.csv(file9)
data10 <- read.csv(file10)
data11 <- read.csv(file11)
data12 <- read.csv(file12)
data13 <- read.csv(file13)
data14 <- read.csv(file14)
data15 <- read.csv(file15)
# 合并数据框
merged_data <- bind_rows(data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15,)

# 查看合并后的数据
print(merged_data)

```

```{r}
write.csv(merged_data, "data/merged_data.csv", row.names = FALSE)
```

```{r}
merged_data <- read.csv("data/merged_data.csv")
title_info <- read.csv("data/Data_TitleInfo.csv")
student_info <- read.csv("data/Data_StudentInfo.csv")
```

```{r}
# 查看数据结构
str(merged_data)
str(title_info)
str(student_info)

# 合并学生信息
data_combined <- merged_data %>%
  left_join(student_info, by = "student_ID") %>%
  left_join(title_info, by = "title_ID")

# 检查合并后的数据
str(data_combined)
write.csv(data_combined, )
```

```{r}
# 读取数据
data <- read.csv('~/Documents/GitHub/ISSS608-WangYuhui/Take-home_Ex/Take-home_Ex03/data/merged_data.csv')

# 查看数据结构
str(data)

# 检查缺失值
missing_values <- colSums(is.na(data))
print(missing_values)

# 可视化缺失值
library(Amelia)
missmap(data, main = "Missing values map")

# 处理缺失值（示例：用均值填充）
data <- data %>% mutate(across(everything(), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .)))
```

```{r}

```
