project:
  type: website

website:
  title: "Visual-Analytics-Fly-Like-a-G6"
  navbar:
    left:
      - href: "Project_Proposal/Group6_project_proposal.html"
        text: "Project Proposal"
      - text: Tasks
        menu:
        - href: "team3/Take_home_Ex3/Take_home_Ex3.html"
          text: "Task1"
        - href: "team3/Take_home_Ex3/Take_home_Ex3.html"
          text: "Task2"
        - href: "team3/Take_home_Ex3/Take_home_Ex3.html"
          text: "Task3"
      - about.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

