project:
  type: website

website:
  title: "Visual-Analytics-Fly-Like-a-G6"
  navbar:
    left:
      - href: "Project_Proposal/Group6_project_proposal.html"
        text: "Project Proposal"
      - text: Detailed steps
        menu:
        - href: "Detailed_steps/DataPrep/DataPrep.html"
          text: "Data Preparation"
        - href: "Detailed_steps/Task1/Task1.html"
          text: "Task1"
        - href: "Detailed_steps/Task2/Task2.html"
          text: "Task2"
        - href: "Detailed_steps/Task3/Task3.html"
          text: "Task3"
        - href: "Detailed_steps/Task4/Task4.html"
          text: "Task4"
      - href: ""
      - text: Shinny app
      - about.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

